openapi: 3.0.0
info:
  title: API
  version: 1.0.0

paths:
  /users/{user_id}/tasks:
    get:
      summary: Get all tasks for a user
      tags:
        - users
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: A list of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
          format: int64
        task:
          type: string
        is_done:
          type: boolean
        user_id:
          type: integer
          format: int64

    Error:
      type: object
      properties:
        message:
          type: string